name: pbdl
description: A starting point for Dart libraries or applications.
version: 2.1.0

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  json_annotation: ^4.8.0
  hex: ^0.2.0
  quick_log: ^1.1.3
  http2: ^2.1.0
  path: ^1.8.3
  azblob: ^2.0.0
  recase: ^4.0.0
  archive: ^3.3.0
  meta: ^1.7.0
  uuid: ^3.0.4
  get_it: ^7.6.7

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^5.0.2
  pedantic: ^1.11.1
  test: ^1.25.0
